name: nice_absence_manager_app
description: "A Flutter for nicely displaying absence information."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  bloc_test: ^9.1.7
  cached_network_image: ^3.4.1
  dart_mappable: ^4.3.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  get_it: ^8.0.2
  injectable: ^2.5.0
  intl: ^0.20.1
  path_provider: ^2.1.5
  share_plus: ^10.1.2

dev_dependencies:
  build_runner: ^2.4.13
  dart_mappable_builder: ^4.3.0
  flutter_gen_runner: ^5.8.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.5.0
  mockito: ^5.4.4
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mock/absences.json
    - assets/mock/members.json
